export const SETUP_PRODUCTS_BEGIN = 'SETUP_PRODUCTS_BEGIN';
export const SETUP_PRODUCTS_SUCCESS = 'SETUP_PRODUCTS_SUCCESS';

export const HANDLE_FILTER_CHANGE = 'HANDLE_FILTER_CHANGE';
export const HANDLE_SORT_CHANGE = 'HANDLE_SORT_CHANGE';
export const HANDLE_SEARCH_CHANGE = 'HANDLE_SEARCH_CHANGE';
export const HANDLE_PAGE_CHANGE = 'HANDLE_PAGE_CHANGE';

export const SETUP_BASKET = 'SETUP_BASKET';
